---
- name: Load setup status
  ansible.builtin.stat:
    path: "/etc/passive_income_setup_complete"
  register: setup_status

- name: Set setup complete fact
  ansible.builtin.set_fact:
    passive_income_setup_complete: "{{ setup_status.stat.exists }}"

- name: Run one-time setup tasks
  when: not passive_income_setup_complete
  block:
    - name: Include prechecks
      ansible.builtin.include_tasks: prechecks.yml

    - name: Include network isolation setup
      ansible.builtin.include_tasks: network_isolation.yml

    - name: Mark setup as complete
      ansible.builtin.file:
        path: "/etc/passive_income_setup_complete"
        state: touch
        mode: '0644'
      become: true

- name: Deploy passive income services if active
  when: deploy_passive_income | bool
  block:
    - name: Check if passive income network exists
      community.docker.docker_network_info:
        name: "{{ passive_income_network_name }}"
      register: network_info

    - name: Create passive income network
      community.docker.docker_network:
        name: "{{ passive_income_network_name }}"
        ipam_config:
          - subnet: "{{ passive_income_network_subnet }}"
      become: true
      when: not network_info.exists

    - name: Include Bitping tasks
      ansible.builtin.include_tasks: bitping.yml
      when: vault_bitping_email | length > 0 and vault_bitping_passwd | length > 0 and bitping_data_path | length > 0

    - name: Include EarnApp tasks
      ansible.builtin.include_tasks: earnapp.yml
      when: vault_earnapp_uuid  | length > 0 and earnapp_data_path | length > 0

    - name: Include EarnFM tasks
      ansible.builtin.include_tasks: earnfm.yml
      when: vault_earnfm_api_key | length > 0

    - name: Include Honeygain tasks
      ansible.builtin.include_tasks: honeygain.yml
      when: vault_honeygain_email | length > 0 and vault_honeygain_passwd | length > 0

    - name: Include IproyalPawns tasks
      ansible.builtin.include_tasks: iproyalpawns.yml
      when: vault_iproyalpawns_email | length > 0 and vault_iproyalpawns_passwd | length > 0

    - name: Include Packetstream tasks
      ansible.builtin.include_tasks: packetstream.yml
      when: vault_packetstream_cid | length > 0

    - name: Include Proxyrack tasks
      ansible.builtin.include_tasks: proxyrack.yml
      when: vault_proxyrack_uuid | length > 0

    - name: Include Mysterium Node tasks
      ansible.builtin.include_tasks: mystnodes.yml
      when: mysterium_node_data_path | length > 0

    - name: Include Repocket tasks
      ansible.builtin.include_tasks: repocket.yml
      when: vault_repocket_email | length > 0 and vault_repocket_api_key | length > 0

    - name: Include Traffmonetizer tasks
      ansible.builtin.include_tasks: traffmonetizer.yml
      when: vault_traffmonetizer_token | length > 0

    - name: Delete passive income related files
      ansible.builtin.file:
        path: /tmp/passive_income
        state: absent
      when: not debug_mode
