---
- name: Check if MystNodes container exists
  community.docker.docker_container_info:
    name: mystNodes
  register: mystnodes_info

- name: Render MystNodes compose file
  ansible.builtin.template:
    src: mystnodes.yml.j2
    dest: /tmp/passive_income/mystnodes.yml
    mode: '0644'
  when: not mystnodes_info.exists

- name: Deploy MystNodes container
  community.docker.docker_compose_v2:
    project_src: /tmp/passive_income
    files:
      - mystnodes.yml
  when: not mystnodes_info.exists
