---
- name: Run prechecks
  when: not passive_income_setup_complete | default(false)
  block:
    - name: Check if running on ARM architecture
      ansible.builtin.command: uname -m
      register: architecture
      changed_when: false

    - name: Install prerequisites for ARM devices
      when: "'arm' in architecture.stdout or 'aarch' in architecture.stdout"
      block:
        - name: Install binfmt-support
          ansible.builtin.apt:
            name: binfmt-support
            state: present
            update_cache: true
          become: true

        - name: Install binfmt emulation layer
          community.docker.docker_container:
            name: binfmt-installer
            image: tonistiigi/binfmt
            command: --install all
            privileged: true
            auto_remove: true
          become: true

        - name: Add binfmt emulation to system crontab
          ansible.builtin.lineinfile:
            path: /etc/crontab
            line: "@reboot root docker run --privileged --rm tonistiigi/binfmt --install all"
            state: present
          become: true
