---
- name: Deploy remote access LITE if requested
  when: deploy_remote_access_LITE | bool
  block:
    - name: Check if home lab Docker network exists
      community.docker.docker_network_info:
        name: "{{ home_lab_network_name }}"
      register: network_info

    - name: Fail if home lab network doesn't exist
      ansible.builtin.fail:
        msg: "Required Docker network '{{ home_lab_network_name }}' does not exist. Please create the network first through the base_network_watchtower role."
      when: not network_info.exists
    
    - name: Create remote_access_lite directory
      ansible.builtin.file:
        path: /tmp/remote_access_lite
        state: directory

    - name: Include noip tasks
      ansible.builtin.include_tasks: noip.yml
      when: vault_noip_username | length > 0 and vault_noip_password | length > 0 and vault_noip_domains | length > 0

    - name: Include wireguard tasks
      ansible.builtin.include_tasks: wireguard.yml
      when: vault_wg_host_url | length > 0

    - name: Include putty tasks
      ansible.builtin.include_tasks: putty.yml
      when: putty_config_path | length > 0

    - name: Delete remote access LITE related files
      ansible.builtin.file:
        path: /tmp/remote_access_lite
        state: absent
      when: not debug_mode



